insert into food (food_name) values ('Hay');
insert into food (food_name) values ('Fish');
insert into food (food_name) values ('Raw meat');
insert into food (food_name) values ('Fruits');
insert into food (food_name) values ('Vegetables');
insert into food (food_name) values ('Insects');
insert into food (food_name) values ('Bamboo');
insert into food (food_name) values ('Nuts');
insert into food (food_name) values ('Seeds');
insert into food (food_name) values ('Eggs');
insert into food (food_name) values ('Bones');
insert into food (food_name) values ('Rodents');
insert into food (food_name) values ('Grass');
insert into food (food_name) values ('Leaves');
insert into food (food_name) values ('Bark');
insert into food (food_name) values ('Nectar');
insert into food (food_name) values ('Live prey');
insert into food (food_name) values ('Mealworms');
insert into food (food_name) values ('Aquatic plants');
insert into food (food_name) values ('Grains');
