INSERT INTO services (service_name, service_category, service_cost) VALUES
  ('Guided tours', 'Educational Services', 357.93),
  ('Educational programs', 'Educational Services', 560.45),
  ('School field trips', 'Educational Services', 357.68),
  ('Conservation workshops', 'Educational Services', 120.94),
  ('Educational lectures', 'Educational Services', 335.02),
  ('Environmental education booths', 'Educational Services', 140.49),
  ('Zoo camps', 'Educational Services', 382.44),
  ('Animal welfare talks', 'Educational Services', 124.69),
  ('Eco-awareness campaigns', 'Educational Services', 94.57),
  ('Animal feeding sessions', 'Animal Interaction', 486.19),
  ('Petting zoo', 'Animal Interaction', 399.59),
  ('Animal encounters', 'Animal Interaction', 340.39),
  ('Keeper talks', 'Animal Interaction', 60.88),
  ('Behind-the-scenes tours', 'Animal Interaction', 315.28),
  ('Wildlife photography sessions', 'Animal Interaction', 569.51),
  ('Live shows', 'Animal Interaction', 149.84),
  ('Animal adoption programs', 'Animal Interaction', 829.37),
  ('Animal art sessions', 'Animal Interaction', 342.3),
  ('Birthday parties', 'Entertainment & Events', 216.58),
  ('Seasonal events', 'Entertainment & Events', 755.08),
  ('Zoo sleepovers', 'Entertainment & Events', 338.87),
  ('Night tours', 'Entertainment & Events', 969.3),
  ('Carousel rides', 'Entertainment & Events', 105.26),
  ('Train rides', 'Entertainment & Events', 84.89),
  ('Playground areas', 'Entertainment & Events', 67.78),
  ('Interactive exhibits', 'Entertainment & Events', 374.01),
  ('Event hosting', 'Entertainment & Events', 461.73),
  ('Corporate event hosting', 'Entertainment & Events', 983.74),
  ('Membership programs', 'Membership & Engagement', 557.63),
  ('Annual passes', 'Membership & Engagement', 256.57),
  ('Volunteer opportunities', 'Membership & Engagement', 0.0),
  ('Group discounts', 'Membership & Engagement', 71.57),
  ('Mobile zoo visits', 'Membership & Engagement', 331.38),
  ('QR code tours', 'Membership & Engagement', 440.68),
  ('Virtual tours', 'Membership & Engagement', 624.19),
  ('Zoo app support', 'Membership & Engagement', 338.01),
  ('Audio guides', 'Membership & Engagement', 71.73),
  ('Food and beverage services', 'Visitor Services', 267.55),
  ('Gift shop', 'Visitor Services', 54.06),
  ('Parking facilities', 'Visitor Services', 294.01),
  ('Locker rental', 'Visitor Services', 292.51),
  ('Stroller rental', 'Visitor Services', 160.99),
  ('Wheelchair rental', 'Visitor Services', 186.31),
  ('First aid services', 'Visitor Services', 0.0),
  ('Lost and found', 'Visitor Services', 125.77),
  ('Accessibility services', 'Visitor Services', 143.56);
