insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Keeper talks', 'Animal Interaction');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal feeding sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('QR code tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Live shows', 'Animal Interaction');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Wheelchair rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Audio guides', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Stroller rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Corporate event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Volunteer opportunities', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal adoption programs', 'Animal Interaction');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Interactive exhibits', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Playground areas', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Environmental education booths', 'Educational Services');
insert into services (service_name, service_category) values ('Locker rental', 'Visitor Services');
insert into services (service_name, service_category) values ('Mobile zoo visits', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Birthday parties', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Eco-awareness campaigns', 'Educational Services');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Gift shop', 'Visitor Services');
insert into services (service_name, service_category) values ('Zoo camps', 'Educational Services');
insert into services (service_name, service_category) values ('Sustainability exhibits', 'Visitor Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Zoo sleepovers', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Annual passes', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Conservation workshops', 'Educational Services');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Wildlife rehabilitation services', 'Visitor Services');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Educational lectures', 'Educational Services');
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('First aid services', 'Visitor Services');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Event hosting', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Educational programs', 'Educational Services');
insert into services (service_name, service_category) values ('Zoo app support', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Night tours', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Wildlife photography sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Food and beverage services', 'Visitor Services');
insert into services (service_name, service_category) values ('Behind-the-scenes tours', 'Animal Interaction');
insert into services (service_name, service_category) values ('Accessibility services', 'Visitor Services');
insert into services (service_name, service_category) values ('Guided tours', 'Educational Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('School field trips', 'Educational Services');
insert into services (service_name, service_category) values ('Virtual tours', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Lost and found', null);
insert into services (service_name, service_category) values ('Animal art sessions', 'Animal Interaction');
insert into services (service_name, service_category) values ('Train rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Membership programs', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Parking facilities', 'Visitor Services');
insert into services (service_name, service_category) values ('Seasonal events', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Petting zoo', 'Animal Interaction');
insert into services (service_name, service_category) values ('Animal encounters', 'Animal Interaction');
insert into services (service_name, service_category) values ('Carousel rides', 'Entertainment & Events');
insert into services (service_name, service_category) values ('Group discounts', 'Membership & Engagement');
insert into services (service_name, service_category) values ('Animal welfare talks', 'Educational Services');
