insert into services (service_name, service_category, service_cost) values ('Guided tours', 'Educational Services', 223);
insert into services (service_name, service_category, service_cost) values ('Educational programs', 'Educational Services', 289);
insert into services (service_name, service_category, service_cost) values ('School field trips', 'Educational Services', 385);
insert into services (service_name, service_category, service_cost) values ('Animal feeding sessions', 'Animal Interaction', 470);
insert into services (service_name, service_category, service_cost) values ('Petting zoo', 'Animal Interaction', 214);
insert into services (service_name, service_category, service_cost) values ('Animal encounters', 'Animal Interaction', 278);
insert into services (service_name, service_category, service_cost) values ('Keeper talks', 'Animal Interaction', 260);
insert into services (service_name, service_category, service_cost) values ('Birthday parties', 'Entertainment & Events', 446);
insert into services (service_name, service_category, service_cost) values ('Zoo camps', 'Educational Services', 322);
insert into services (service_name, service_category, service_cost) values ('Wildlife photography sessions', 'Animal Interaction', 227);
insert into services (service_name, service_category, service_cost) values ('Behind-the-scenes tours', 'Animal Interaction', 351);
insert into services (service_name, service_category, service_cost) values ('Volunteer opportunities', 'Membership & Engagement', 620);
insert into services (service_name, service_category, service_cost) values ('Conservation workshops', 'Educational Services', 434);
insert into services (service_name, service_category, service_cost) values ('Animal adoption programs', 'Animal Interaction', 646);
insert into services (service_name, service_category, service_cost) values ('Membership programs', 'Membership & Engagement', 296);
insert into services (service_name, service_category, service_cost) values ('Annual passes', 'Membership & Engagement', 361);
insert into services (service_name, service_category, service_cost) values ('Gift shop', 'Visitor Services', 370);
insert into services (service_name, service_category, service_cost) values ('Food and beverage services', 'Visitor Services', 232);
insert into services (service_name, service_category, service_cost) values ('Event hosting', 'Entertainment & Events', 540);
insert into services (service_name, service_category, service_cost) values ('Night tours', 'Entertainment & Events', 288);
insert into services (service_name, service_category, service_cost) values ('Seasonal events', 'Entertainment & Events', 412);
insert into services (service_name, service_category, service_cost) values ('Interactive exhibits', 'Entertainment & Events', 440);
insert into services (service_name, service_category, service_cost) values ('Train rides', 'Entertainment & Events', 349);
insert into services (service_name, service_category, service_cost) values ('Carousel rides', 'Entertainment & Events', 574);
insert into services (service_name, service_category, service_cost) values ('Playground areas', 'Entertainment & Events', 278);
insert into services (service_name, service_category, service_cost) values ('Accessibility services', 'Visitor Services', 194);
insert into services (service_name, service_category, service_cost) values ('Group discounts', 'Membership & Engagement', 605);
insert into services (service_name, service_category, service_cost) values ('Educational lectures', 'Educational Services', 263);
insert into services (service_name, service_category, service_cost) values ('Wildlife rehabilitation services', 'Visitor Services', 276);
insert into services (service_name, service_category, service_cost) values ('Corporate event hosting', 'Entertainment & Events', 654);
insert into services (service_name, service_category, service_cost) values ('Live shows', 'Animal Interaction', 423);
insert into services (service_name, service_category, service_cost) values ('Mobile zoo visits', 'Membership & Engagement', 165);
insert into services (service_name, service_category, service_cost) values ('Animal art sessions', 'Animal Interaction', 607);
insert into services (service_name, service_category, service_cost) values ('Zoo sleepovers', 'Entertainment & Events', 340);
insert into services (service_name, service_category, service_cost) values ('Eco-awareness campaigns', 'Educational Services', 259);
insert into services (service_name, service_category, service_cost) values ('QR code tours', 'Membership & Engagement', 411);
insert into services (service_name, service_category, service_cost) values ('Virtual tours', 'Membership & Engagement', 258);
insert into services (service_name, service_category, service_cost) values ('Audio guides', 'Membership & Engagement', 480);
insert into services (service_name, service_category, service_cost) values ('First aid services', 'Visitor Services', 675);
insert into services (service_name, service_category, service_cost) values ('Lost and found', null, 442);
